MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
#  WEIGHTS: "./datasets/cache/model_final_94dc52.pkl"
#  WEIGHTS: "/home/yili/ObjectEmbedding/Mask2Former/output/model_0004999.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("amazon_syn_v1_train_shard_000000",)
  TEST: ("amazon_image_real_v1_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (12000, )
  MAX_ITER: 16000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
  CHECKPOINT_PERIOD: 1000
INPUT:
  IMAGE_SIZE: 256
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "amazon_v0"
  MIN_SIZE_TRAIN: (128, )
  MAX_SIZE_TRAIN: 360
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 256
  SAMPLING_FRAME_NUM: 2
  CROP:
    ENABLED: False
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 10
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
VERSION: 2
